# Reads GEMINI_API_KEY or GOOGLE_API_KEY from ..\.env → ..\env-config.js
$ErrorActionPreference = "Stop"
$extRoot = Split-Path -Parent $PSScriptRoot
$envPath = Join-Path $extRoot ".env"
$outPath = Join-Path $extRoot "env-config.js"

if (-not (Test-Path $envPath)) {
  Write-Error "Missing .env at $envPath"
}

$raw = (Get-Content -Raw -Encoding UTF8 $envPath) -replace "^\uFEFF", ""
$gemini = ""
$google = ""
foreach ($line in ($raw -split "`r?`n")) {
  $t = $line.Trim()
  if (-not $t -or $t.StartsWith("#")) { continue }
  $eq = $t.IndexOf("=")
  if ($eq -lt 1) { continue }
  $k = $t.Substring(0, $eq).Trim()
  $v = $t.Substring($eq + 1).Trim()
  if (($v.StartsWith('"') -and $v.EndsWith('"')) -or ($v.StartsWith("'") -and $v.EndsWith("'"))) {
    $v = $v.Substring(1, $v.Length - 2)
  }
  if ($k -eq "GEMINI_API_KEY") { $gemini = $v }
  if ($k -eq "GOOGLE_API_KEY") { $google = $v }
}

$key = if ($gemini) { $gemini } else { $google }
$json = ($key | ConvertTo-Json -Compress)
$banner = "/* Generated by scripts/write-env-config.ps1 — do not commit if this contains a real key. */`n"
Set-Content -Path $outPath -Value ($banner + "var GEMINI_API_KEY_FROM_ENV = $json;") -Encoding UTF8
if ($key) {
  Write-Host "Wrote env-config.js ($($key.Length) chars)."
} else {
  Write-Host "Wrote env-config.js with empty key — set GEMINI_API_KEY or GOOGLE_API_KEY in .env."
}
